%
% PANEL DE CONTROL
%
% Parte inicial de la aplicacion, organiza el panel y las figuras. Tambien
% capta las variables tales como 
% Frec de corte, Fact Der/Izq, w0, w1, w2, ... que sirven para el funcionamiento del programa
% Ajusta las figuras, las variables para modificar el texto, ... etc.
%
% Diagrama de Bloques de la Herramienta de Medida:
%
% Panel --> Ensayo --> Medir --> Prueba --> tiempo2frec --> Desp_barra --> Desplaza --> Selec_bloque --> Cadenas3 --> CreaCombianaciones --> Alg_Comprueba_Comb_válidas --> Escribe
%                      |                                  |                                           |
%                      ---> filtrar_eeg                   ---> filtrado                               ---> dibuja_cambio_predicción
%
% Vea tambien: pulsar
%
%
% Juan Antonio Lara Domínguez - Dpto. de Tecnología Electrónica - Universidad de Málaga - 2007
% Modificado: Francisco Velasco, Octubre 2008
%--------------------------------------------------------------------------------------------------------------

% Limpiar todo el entorno Matlab:
close all; %/ cerramos todas las figuras que haya abiertas
clear all; %/ Borra todas las variables y algunas cosas mas
global COLOR_FONDO color_texto;  %colores de la pantalla del sujeto
COLOR_FONDO_TEXTOS= [.5 .5 .5];             %Usado para el fondo de los frame, y logicamente el fondo de los textos
COLOR_FONDO=[1 1 1];                        %Color del fondo de los cuadros que rellena el usuario
color_texto=[0 0 0];                        % Color de texto del panel
global barra_min
global umbral_selec2
global closingFigure

global Fs tam_ventana solape orden t_cursor t_objetivo t_analisis d_analisis d_prueba;
alt=0.5;           %Altura

%/ Parametros de cada sujeto (a introducir en el panel)
global fc1 fc2 t_reset w0 w1 w2 fact_der fact_izq barThreshold tiempo_en_bloq t_pause sujeto sesion

global metodo vel giro explore;             %Son los metodos de funcionamiento disponibles
%global cell_metodo cell_vel;
% Indica el fin de la ejecución
global closingTime;
closingTime = 0;

cell_metodo={'Continuo' 'Discreto'};   %Usado para el menu pop-up
cell_vel={'1' '2' '3'};   %Usado para el menu pop-up
cell_giro={'Continuo' 'Discreto'};
cell_explore={'Evaluación' 'Objetivo'};


% ESTADÍSTICOS--------------
% cada una de las siguientes vbles será un vector de 3 posiciones, una para
% cada comando (avanzar, girar dcha y girar izqd)
global num_vueltas t_total t_bloque num_eleccx t_invocax;
num_vueltas = [0 0 0];
t_total = [0 0 0];
t_bloque = [0 0 0];
num_eleccx = [0 0 0];
t_invocax = 0;

%---------------------------------------------------------------------

global cell_seleccion seleccion2             %NUEVO!!!!!!!!!!!!!!!!!!!!!!
cell_seleccion={'1' '2'};

%---------------------------------------------------------------configuración general de la ventana de texto

Fs=128;                %/ hay que poner 128(130 no)
tam_ventana=4;  %/ hay que poner 4(13 no)
solape=60;  %/ hay que poner 60(0 no) (ver tiempo2frec el tamaño)
orden=floor(tam_ventana/2);
t_cursor= 1;
t_objetivo= 3;
t_analisis= 4;
d_analisis= 5.6;
d_prueba=4000;
 % Existe el fichero de configuración, cargo las variables
if exist('AsincronoIntegrado/ensayo_config.mat','file') == 2            
     load ensayo_config;
     sesion = sesion + 1;     
else  
    fc1=8;           
    fc2=15; 
    t_reset=1;     
    w0=0;
    w1=1;  
    w2=0;
    fact_der=1;
    fact_izq=1; 
    tiempo_en_bloq=1;
    vel=1;
    metodo=1;
    giro=1;
    explore = 1.;
    seleccion2=1;
    barra_min=0.45;  
    umbral_selec2=0.6;
    t_pause = 2;
    sesion = 1;
    barThreshold = 0.7;
end,    

%---------------------------------------------------- configuración general de la ventana del PANEL DE CONTROL
%--------------------------------------------------------------------------------------------------
global fig_panel;
fig_panel = 1;
figure(fig_panel);
set(figure(fig_panel), ...
	'NumberTitle','off', ...
	'Name','Editor de Texto controlado por señales EEG', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
    'KeyPressFcn',@pulsar, ...
	'Position',[8.4 7.5 9.9 7.9], ...
    'Pointer','arrow');
%---------------------------------------------------------------------variables ///21-2-07


%3---ORGANIZACIÓN DEL ENSAYO-----------------------------------------------------------------------------------
frameHndl_ensayo=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[.4 1.8 9.1 5.6], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');

%--------------------------------------------------------------------------/// frec corte 1
textHndl_fc1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 4.65 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte inferior',...
   'String','Fc Inf:');

Accion_fc1=['fc1=str2num(get(editHndl_fc1,''String''));'];
editHndl_fc1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 4.75 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte inferior',...
   'String',fc1, ...
   'CallBack',Accion_fc1);
%--------------------------------------------------------------------------/// frec corte 2
textHndl_fc2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 3.95 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte superior',...
   'String','Fc Sup:');

Accion_fc2=['fc2=str2num(get(editHndl_fc2,''String''));'];
editHndl_fc2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 4.05 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte superior',...
   'String',fc2, ...
   'CallBack',Accion_fc2);
%--------------------------------------------------------------------------/// fact_der
textHndl_fact_der = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 3.25 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor derecha',...
   'String','F. Der:');

Accion_fact_der=['fact_der=str2num(get(editHndl_fact_der,''String''));'];
editHndl_fact_der=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 3.35 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor derecha',...
   'String',fact_der, ...
   'CallBack',Accion_fact_der);
%--------------------------------------------------------------------------/// fact_izq
textHndl_fact_izq = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 2.55 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor izquierda',...
   'String','F. Izq:');

Accion_fact_izq=['fact_izq=str2num(get(editHndl_fact_izq,''String''));'];
editHndl_fact_izq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 2.65 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor izquierda',...
   'String',fact_izq, ...
   'CallBack',Accion_fact_izq);

%--------------------------------------------------------------------------%/// tiempo de t_reset
textHndl_w0 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 4.65 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w0',...
   'String','w0:');

Accion_w0=['w0=str2num(get(editHndl_w0,''String''));'];
editHndl_w0=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 4.75 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w0',...
   'String',w0, ...
   'CallBack',Accion_w0);
%--------------------------------------------------------------------------/// w1
textHndl_w1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 3.95 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w1',...
   'String','w1:');

Accion_w1=['w1=str2num(get(editHndl_w1,''String''));'];
editHndl_w1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 4.05 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w1',...
   'String',w1, ...
   'CallBack',Accion_w1);
%--------------------------------------------------------------------------/// w2
textHndl_w2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 3.25 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','w2',...
   'String','w2:');

Accion_w2=['w2=str2num(get(editHndl_w2,''String''));'];
editHndl_w2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 3.35 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w2',...
   'String',w2, ...
   'CallBack',Accion_w2);
%--------------------------------------------------------------------------
%/// T. Reset
textHndl_t_reset = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 2.55 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','t_reset',...
   'String','T. Reset:');

Accion_t_reset=['t_reset=str2num(get(editHndl_t_reset,''String''));'];
editHndl_t_reset=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[4.3 2.65 .6 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo de pause',...
   'String',t_reset, ...
   'CallBack',Accion_t_reset);

%--------------------------------------------------------------------------/// w0
textHndl_umbral = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 3.95 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Umbral del usuario',...
   'String','Umbral del usuario:');

Accion_umbral=['barThreshold=str2num(get(editHndl_umbral,''String''));'];
editHndl_umbral=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[7.8 4.05 1.3 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Umbral del usuario',...
   'String',barThreshold, ...
   'CallBack',Accion_umbral);
%--------------------------------------------------------------------------/// vel
textHndl_vel= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 3.25 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Velocidad de rotación de la flecha',...
   'String','Velocidad de rotación:');

Accion_popup_vel=['vel= get(popupHndl_vel,''Value'');'];
pop_string_vel=char(cell_vel(1));
for i= 2:3,
   pop_string_vel=[pop_string_vel '|' char(cell_vel(i))];
end;
popupHndl_vel = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[8.3 3.35 0.8 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_vel,...
   'Value',vel,...
   'CallBack',Accion_popup_vel);

%--------------------------------------------------------------- metodo de
%avance
textHndl_metodo = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 4.65 2.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Avance continuo o discreto',...
   'String','Avance:');

Accion_popup_metodo=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos:
      'metodo= get(popupHndl_metodo,''Value'');', ...
   ];
%Construccion del string del popup:
pop_string=char(cell_metodo(1));
for i= 2:2,
   pop_string=[pop_string '|' char(cell_metodo(i))];
end;
popupHndl_metodo = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[7.4 4.75 1.7 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string,...
   'Value',metodo,...
   'CallBack',Accion_popup_metodo);

%--------------------------------------------------------------------------/// Tiempo de seleccion
textHndl_tiempo_en_bloq= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 2.55 3.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Tiempo para seleccionar un bloque',...
   'String','Tiempo de selección:');

Accion_tiempo_en_bloq=['tiempo_en_bloq = str2num(get(editHndl_tiempo_en_bloq,''String''));'];
editHndl_tiempo_en_bloq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[8.4 2.65 .7 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo necesario para que un bloque sea seleccionado',...
   'String',tiempo_en_bloq, ...
   'CallBack',Accion_tiempo_en_bloq);

%------------------------------------------NUEVO!!!!!! EL "modo de seleccion"

textHndl_seleccion2= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[6.35 1.85 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Método de selección de bloque',...
   'String','Mét.Selecc.:');

Accion_popup_seleccion2=['seleccion2= get(popupHndl_seleccion2,''Value'');'];
pop_string_seleccion2=char(cell_seleccion(1));
for i= 2:2,
   pop_string_seleccion2=[pop_string_seleccion2 '|' char(cell_seleccion(i))];
end;
popupHndl_seleccion2 = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[8.3 1.95 0.8 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_seleccion2,...
   'Value',seleccion2,...
   'CallBack',Accion_popup_seleccion2);

%-----------------------------------%NUEVO!!! lONG min. DE LA BARRA!!! 

textHndl_barra_min = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3.3 1.85 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','L.BAR',...
   'String','L.Bar:');

Accion_barra_min=['barra_min=str2num(get(editHndl_barra_min,''String''));'];
editHndl_barra_min=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[4.1 1.95 0.8 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','L.BAR',...
   'String',barra_min, ...
   'CallBack',Accion_barra_min);


%UMBRAL DE DETENCIÓN
textHndl_umbral_selec2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.45 1.85 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Umbral Detención',...
   'String','Umbral Det:');

Accion_umbral_selec2=['umbral_selec2=str2num(get(editHndl_umbral_selec2,''String''));'];
editHndl_umbral_selec2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.9 1.95 0.8 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Umb.Det.',...
   'String',umbral_selec2, ...
   'CallBack',Accion_umbral_selec2);



%-----------------------------------------------------------------------

%4---MENÚ DE BOTONES---------------------------------------------------------------------
frameHndl_botones=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[1.5 .05 7 1.5], ....
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');
%--------------------------------------------------------------------------pruebas tipo 1

Accion_push_iniciar=[...        
        'if isempty(fc1|fc2|t_reset|w0|w1|w2|fact_der|fact_izq|tiempo_en_bloq|t_pause|sujeto|sesion)',...
        'fig_aviso = 2;',...
        'figure(fig_aviso);',...
        'aviso([''Complete todos los parametros del panel''], figure(fig_aviso));',...    
        'else,',...
        'save ensayo_config.mat fc1 fc2 t_reset w0 w1 w2 fact_der fact_izq t_pause explore ', ...
        'vel metodo seleccion2 barra_min umbral_selec2 tiempo_en_bloq sujeto sesion giro barThreshold;', ...    
        'close(fig_panel);',... 
        'StartVR;',...
        'Ensayo2;',...            
        'end'];       
pushHndl_iniciar=uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[2 .3 6 1], ...
    'BackgroundColor',COLOR_FONDO_TEXTOS, ... %Color del fondo
    'ForegroundColor',[0 0 0], ...
    'FontSize',15,...
    'ToolTipString','Iniciar Ensayo con la configuración establecida',...
    'String','Iniciar aplicación', ...
	'CallBack',Accion_push_iniciar);



% ------------------------------------------------------------------------

%/// T. Pause
textHndl_t_pause = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.85 6.35 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','t_pause',...
   'String','Tiempo de pausa:');

Accion_t_pause=['t_pause=str2num(get(editHndl_t_pause,''String''));'];
editHndl_t_pause=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[8.45 6.45 .6 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo de pause',...
   'String',t_pause, ...
   'CallBack',Accion_t_pause);

%--------------------------------------------------------------------------

%/// Identificador de sujeto
textHndl_sujeto = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.75 5.45 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Sujeto',...
   'String','Sujeto:');

Accion_sujeto=['sujeto = get(editHndl_sujeto,''String'');'];
editHndl_sujeto=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.95 5.55 .8 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Sujeto',...
   'String',sujeto, ...
   'CallBack',Accion_sujeto);

%--------------------------------------------------------------------------

%/// Identificador de sesion
textHndl_sesion = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[2.9 5.45 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Sesion',...
   'String','Sesion:');

Accion_sesion=['sesion = str2num(get(editHndl_sesion,''String''));'];
editHndl_sesion=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[4.1 5.55 .8 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','sesion',...
   'String',sesion, ...
   'CallBack',Accion_sesion);


%--------------------------------------------------------------- metodo de
%giro
textHndl_giro = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 5.45 1 alt], ... [2.9 5.45 3 alt][4.1 5.55 .8 alt]
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Giro continuo o discreto',...
   'String','Giro:');

Accion_popup_giro=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos:
      'giro = get(popupHndl_giro,''Value'');', ...
   ];
%Construccion del string del popup:
pop_string_giro=char(cell_giro(1));
for i= 2:2,
   pop_string_giro=[pop_string_giro '|' char(cell_giro(i))];
end;
popupHndl_giro = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[7.4 5.55 1.7 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_giro,...
   'Value',giro,...
   'CallBack',Accion_popup_giro);



%--------------------------------------------------------------- metodo de
%exploracion
textHndl_explore = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.75 6.35 2 alt], ... 
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Evaluación o Búsqueda de objetivo',...
   'String','Modo:');

Accion_popup_explore=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos:
      'explore = get(popupHndl_explore,''Value'');', ...
   ];
%Construccion del string del popup:
pop_string_explore=char(cell_explore(1));
for i= 2:2,
   pop_string_explore=[pop_string_explore '|' char(cell_explore(i))];
end;
popupHndl_explore = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[1.95 6.45 2 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_explore,...
   'Value',explore,...
   'CallBack',Accion_popup_explore);


%--------------------------------------------------------------------------
% Una figura que detecta la pulsación de una tecla y cierra la aplicación

closingFigure = 2;
set(figure(closingFigure),'WindowStyle','normal',...   
                'visible','on',...
                'Resize','off',...
                'Name','Cerrar aplicación',...
                'MenuBar','none',...
                'ToolBar','none',...
                'Selected','off',...
                'NumberTitle', 'off',...
                'KeyPressFcn','closingTime = 1;',...               
                'Position', [0,-20,100,10]); 
figure(closingFigure);       
%-------------------------
labels = str2mat( ...
     '&Salir', ...
     '>&Salir de Sesion^s', ...
     '>-------', ...
     '>&Salir de Matlab^m', ...
     '&Ayuda' ...
     ); %labels
 
 call_Salir=[...
     'Sesion_Salir;'...
  ]; %Call_Salir

  call_SalirDeMatlab=[...
     'SalirDeMatlab;'...
  ]; %Call_SalirDeMatlab
calls = str2mat( ...
     '', ...
     call_Salir, ...	%es un programa que hay hecho
     '', ...
     call_SalirDeMatlab, ... %es un CallBack que hay hecho
     'Sesion_Ayuda' ... %Es un programa
     );
handles = makemenu(gcf, labels, calls);   

