%
% PANEL DE CONTROL
%
% Parte inicial de la aplicacion, organiza el panel y las figuras. Tambien capta las variables tales como 
% Frec de corte, Fact Der/Izq, w0, w1, w2, ... que sirven para el funcionamiento del programa
% Ajusta las figuras, las variables para modificar el texto, ... etc.
%
% Diagrama de Bloques de la Herramienta de Medida:
%
% Panel --> Ensayo --> Medir --> Prueba --> tiempo2frec --> Desp_barra --> Desplaza --> Selec_bloque --> Selec_letra --> Escribe
%             |                                      |                                           |
%             ---> filtrar_eeg ---> filtrado         ---> filter                                 ---> dibujo(rued_aux)
%
%
% Vea tambien: Dibujo, Ensayo, pulsar
%
%
% Tomas Perez Lisbona - Dpto. de Tecnología Electrónica - Universidad de Málaga - 2007
%--------------------------------------------------------------------------------------------------------------

% Limpiar todo el entorno Matlab:
close all; %/ cerramos todas las figuras que haya abiertas
clear all; %/ Borra todas las variables y algunas cosas mas

% -----------------------------------------------------------------------Ajuste del color:
whitebg('k'); %/ esta instrucción es muy util, cambia el color de fondo por defecto a un tono gris,
%LO BUENO, es que ademas cambia otras propiedades como el color del texto, esto es muy util por ejemplo
%para los legend, pues si no escribiria en negro y no se veria.
%-----------------------------------------------------------------------------------


global COLOR_FONDO color_texto color_gris;  %colores de la pantalla del sujeto
COLOR_FONDO_TEXTOS= [.5 .5 .5];             %Usado para el fondo de los frame, y logicamente el fondo de los textos
COLOR_FONDO=[1 1 1];                        %Color del fondo de los cuadros que rellena el usuario
color_texto=[0 0 0];                        % Color de texto del panel
color_gris=[.8 .8 .8];                      %/ color gris para el fondo de cada letra de la rueda

%Las figuras para las distintas ventanas son:
global fig_panel fig_sujeto fig_texto fig_rueda fig_rueda_aux flecha1;
fig_panel=1;        %Para el panel de control.
fig_sujeto=8;       %Para la ventana del sujeto
fig_rueda=4;        %La ventana de la rueda principal
fig_rueda_aux=5;    %ventana de rueda auxiliar
fig_texto=6;        %ventana de texto
fig_fondo=7;        %dibujo una figura de fondo como papel tapiz
%---------------------------------------------------------------------------- Variables:

global Fs tam_ventana solape orden t_cursor t_objetivo t_analisis d_analisis d_prueba c1 c2;
alt=0.5;           %Altura

global tecla selec principal    %%// la uso para seleccionar el bloque en la rueda (9-4-07)
tecla=0;
selec=0;
principal=1;

global borrar palabra_ant       %%// Esto es para borrar una letra 18-4-07
borrar=0;               
palabra_ant=' ';

global acaba                    %%// para acabar el programa        
acaba=0;

%----------------->>---------------------------------Variables globales usadas por ModelarFiltros.m--------->>
global Num Den; %fdatool exporta las variables al Workspace, y saber si esas variables han
%                aparecido o no en el Workspace es la unica forma que tenemos de saber cuando
%                se ha terminado con fdatool. Por tanto, es necesario que usemos unas variables
%                'Num' y 'Den' globales.(Para comprender mejor esto, ver lo que se hace cuando
%                se llama a fdatool en NumDenFiltro1 y NumDenFiltro2).
Num=[];%Las definimos como vacias.
Den=[];%Las definimos como vacias.   

global fc1 fc2 pausa w0 w1 w2 fact_der fact_izq umbral tiempo_en_bloq%/ Parametros de cada sujeto (a introducir en el panel)
global mueve cuenta             %/ mueve la flecha (16-3-07)
mueve=90;
cuenta=0;

global cell_metodos metodo cell_vel vel;             %Son los metodos de funcionamiento disponibles
cell_metodos={'Continuo' 'Impulsos'};   %Usado para el menu pop-up de modo de funcionamiento (ahora solo está diseñado el modo continuo)
cell_vel={'1' '2' '3'};                 %Usado para el menu pop-up de velocidad (1,2 o 3º por desplazamiento)

global cell_color color cod_color tamano  cell_colorf colorf cod_colorf;        %Son los colores disponibles para el texto
cell_color={'Negro' 'Gris' 'Rojo' 'Rosa' 'Azul' 'Verde' 'Amarillo' 'Blanco'};   %Usado para el menu pop-up de color de letra

cod_color={[0 0 0] [0.5 0.5 0.5] [1 0 0] [1 0 1] [0 0 1] [0 1 0] [1 1 0] [1 1 1]};
cell_colorf={'Blanco' 'Rojo' 'Rosa' 'Azul' 'Verde' 'Amarillo' 'Gris' 'Negro'};   %Usado para el menu pop-up color de fondo
cod_colorf={[1 1 1] [1 0 0] [1 0 1] [0 0 1] [0 1 0] [1 1 0] [0.5 0.5 0.5] [0 0 0]};

global cell_estilo estilo cell_grosor grosor cell_mayus mayus   % estilo de fuente
cell_estilo= {('Normal') ('Cursiva')};
cell_grosor= {('Normal') ('Negrita')};
cell_mayus= {('Mayusculas') ('minusculas')};

%----------------------------------------------------------------------------------------------------------------<<
%--------------------------------Predibujamos todas las figuras para darles ciertas propiedades y poder ahorrar tiempo mas tarde:
set(0,'Units','pixels'),                    %Por defecto usaremos pixels
Screensize=get(0,'Screensize');             %Ahora sabemos el tamaño de nuestra pantalla en centimetros
Screensize=[Screensize(3) Screensize(4)];   %Screensize(3) es el ancho de la ventana principal, osea el monitor

%---------------------------------------------------------------configuración general de la ventana de texto

Fs=128;                 'set(editHndl_Fs,''String'',num2str(Fs))';                  %/ hay que poner 128(130 no)
tam_ventana=4;          'set(editHndl_tam_ventana,''String'',num2str(tam_ventana))'; %/ hay que poner 4(13 no)
solape=60;              'set(editHndl_solape,''String'',num2str(solape))'; %/ hay que poner 60(0 no) (ver tiempo2frec el tamaño)
orden=floor(tam_ventana/2);	'set(editHndl_orden,''String'',num2str(orden))';
t_cursor= 1;		    'set(editHndl_t_cursor,''String'',num2str(t_cursor))';
t_objetivo= 3;          'set(editHndl_t_objetivo,''String'',num2str(t_objetivo))';
t_analisis= 4;          'set(editHndl_t_analisis,''String'',num2str(t_analisis))';
d_analisis= 5.6;	    'set(editHndl_d_analisis,''String'',num2str(d_analisis))';
d_prueba=4000;           'set(editHndl_d_prueba,''String'',num2str(d_prueba))';     %/ duración de la prueba, hay que
                            %poner un tiempo grande, porque la DAQ no puede estar muestreando un tiempo indeterminado
c1='C3';    		    'set(editHndl_c1,''String'',''C3'')';
c2='C4';		        'set(editHndl_c2,''String'',''C4'')';
umbral=0.28;            'set(editHndl_umbral,''String'',''Umbral'')';
      
if exist('ensayo_config.mat')==2, % Existe el fichero de configuración, cargo las variables
    load ensayo_config;
else,    % Si no existe el fichero cargo estas variables 
    fc1=8;              'set(editHndl_fc1,''String'',num2str(fc1))';            
    fc2=12;             'set(editHndl_fc2,''String'',num2str(fc2))';
    pausa=3;            'set(editHndl_pausa,''String'',num2str(pausa))';      
    w0=0;               'set(editHndl_w0,''String'',num2str(w0))';
    w1=1;               'set(editHndl_w1,''String'',num2str(w1))';  
    w2=0;               'set(editHndl_w2,''String'',num2str(w2))';
    fact_der=1;         'set(editHndl_fact_der,''String'',num2str(fact_der))';  
    fact_izq=1;         'set(editHndl_fact_izq,''String'',num2str(fact_izq))'; 
    tiempo_en_bloq=0.7;  'set(editHndl_tiempo_en_bloq,''String'',num2str(tiempo_en_bloq))'; 
    mayus=1;
    vel=1;
    metodo=1;
    color=1;
    colorf=1;
    tamano=40;
    estilo=1;
    grosor=1;
end,
    
%-----------------------------------------------------------------------------------------------------------------
figure(fig_fondo)               % Esta figura es para tener un fondo liso en la aplicación
set(figure(fig_fondo), ...
	'NumberTitle','off', ...
	'Name','Fondo', ...    
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
    'Color', color_gris, ...
    'KeyPressFcn',@pulsar, ...
	'Position',[0 0 30 20.5], ...
    'Pointer','arrow');

%-----------------------------------------------------------------------------------------------------------------
figure(fig_texto);                  % figura donde va estar representado el texto que se vaya seleccionando
set(figure(fig_texto), ...
	'NumberTitle','off', ...
	'Name','Texto', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
    'KeyPressFcn',@pulsar, ...
	'Position',[0.05 0.9 26.95 3.2], ...
    'Pointer','arrow');

frameHndl_texto=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[0.3 0.3 26.3 2.6], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');

Accion_texto=['texto=get(editHndl_texto,''String'');'];
editHndl_texto=uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[.6 .6 25.7 2], ...
   'BackgroundColor',cod_colorf{colorf}, ... %Color del fondo
   'ForegroundColor',cod_color{color}, ...
   'ToolTipString','Escriba aquí el texto',...
   'CallBack',Accion_texto);

%---------------------------------------------------------Diseño de la Ventana de Juego

fig_rueda=open('rueda.fig');
figure(fig_rueda);
set(figure(fig_rueda), ...
	'NumberTitle','off', ...
	'Name','Seleccion de letra', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'ToolBar','none', ...
    'Units','cent', ...
    'KeyPressFcn',@pulsar, ...
    'Position',[6.1 4.9 14 14], ...
    'Pointer','arrow');

dibujo(fig_rueda);                  %/ llamo a "dibujo" para pintar la rueda principal
flecha1=plot([1 1],[1 1.4],'color',[1 0 0],'LineWidth',6);   %/ pinto la flecha de la rueda principal

%---------------------------------------------------- configuración general de la ventana del PANEL DE CONTROL
%--------------------------------------------------------------------------------------------------
figure(fig_panel);
set(figure(fig_panel), ...
	'NumberTitle','off', ...
	'Name','Editor de Texto controlado por señales EEG', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
    'KeyPressFcn',@pulsar, ...
	'Position',[8.4 7.5 9.9 7.9], ...
    'Pointer','arrow');

%2---CONFIGURACIÓN DE LOS PARAMETROS DEL TEXTO---------------------------------------------------------------------
frameHndl_parametros=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[.4 5.8 9.1 1.7], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');

%--------------------------------------------------------------------------/// color de la fuente
textHndl_color = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.6 6.65 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Color del texto',...
   'String','Color texto:');

Accion_popup_color=['color= get(popupHndl_color,''Value'');'];
pop_string_color=char(cell_color(1));
for j= 2:8,
   pop_string_color=[pop_string_color '|' char(cell_color(j))];
end;
popupHndl_color = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[2.2 6.75 1.6 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_color,...
   'Value',color,...
   'CallBack',Accion_popup_color);

%--------------------------------------------------------------------------/// color del fondo
textHndl_colorf = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.6 5.9 1.6 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Color de fondo',...
   'String','Color fondo:');

Accion_popup_colorf=['colorf= get(popupHndl_colorf,''Value'');'];
pop_string_colorf=char(cell_colorf(1));
for j= 2:8,
   pop_string_colorf=[pop_string_colorf '|' char(cell_colorf(j))];
end;
popupHndl_colorf = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[2.2 6 1.6 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_colorf,...
   'Value',colorf,...
   'CallBack',Accion_popup_colorf);


%--------------------------------------------------------------------------/// Tamaño de la fuente
textHndl_tamano = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[7.2 5.9 1.1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Tamaño de fuente',...
   'String','Tamaño:');

Accion_tamano=['tamano=str2num(get(editHndl_tamano,''String''));'];
editHndl_tamano=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[8.4 6 0.7 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tamaño del texto',...
   'String',tamano, ...
   'CallBack',Accion_tamano);

%--------------------------------------------------------------------------/// Estilo de la fuente
textHndl_estilo = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[4 6.65 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Estilo de texto',...
   'String','Cursiva:');

Accion_popup_estilo=['estilo= get(popupHndl_estilo,''Value'');'];
pop_string_estilo=char(cell_estilo(1));
for j= 2:2,
   pop_string_estilo=[pop_string_estilo '|' char(cell_estilo(j))];
end;
popupHndl_estilo = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[5.1 6.75 1.6 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_estilo,...
   'Value',estilo,...
   'CallBack',Accion_popup_estilo);

%--------------------------------------------------------------------------/// Estilo de la fuente
textHndl_grosor = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[4 5.9 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Estilo de texto',...
   'String','Negrita:');

Accion_popup_grosor=['grosor= get(popupHndl_grosor,''Value'');'];
pop_string_grosor=char(cell_grosor(1));
for j= 2:2,
   pop_string_grosor=[pop_string_grosor '|' char(cell_grosor(j))];
end;
popupHndl_grosor = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[5.1 6 1.6 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_grosor,...
   'Value',grosor,...
   'CallBack',Accion_popup_grosor);

%--------------------------------------------------------------------------/// Mayuscula

Accion_popup_mayus=['mayus= get(popupHndl_mayus,''Value'');'];
pop_string_mayus=char(cell_mayus(1));
for j= 2:2,
   pop_string_mayus=[pop_string_mayus '|' char(cell_mayus(j))];
end;
popupHndl_mayus = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[6.9 6.75 2.2 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_mayus,...
   'Value',mayus,...
   'CallBack',Accion_popup_mayus);


%3---ORGANIZACIÓN DEL ENSAYO-----------------------------------------------------------------------------------
frameHndl_ensayo=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[.4 2.4 9.1 3.1], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');

%--------------------------------------------------------------------------/// frec corte 1
textHndl_fc1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 4.65 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte inferior',...
   'String','Fc Inf:');

Accion_fc1=['fc1=str2num(get(editHndl_fc1,''String''));'];
editHndl_fc1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 4.75 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte inferior',...
   'String',fc1, ...
   'CallBack',Accion_fc1);
%--------------------------------------------------------------------------/// frec corte 2
textHndl_fc2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 3.95 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte superior',...
   'String','Fc Sup:');

Accion_fc2=['fc2=str2num(get(editHndl_fc2,''String''));'];
editHndl_fc2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 4.05 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte superior',...
   'String',fc2, ...
   'CallBack',Accion_fc2);
%--------------------------------------------------------------------------/// fact_der
textHndl_fact_der = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 3.25 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor derecha',...
   'String','F. Der:');

Accion_fact_der=['fact_der=str2num(get(editHndl_fact_der,''String''));'];
editHndl_fact_der=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 3.35 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor derecha',...
   'String',fact_der, ...
   'CallBack',Accion_fact_der);
%--------------------------------------------------------------------------/// fact_izq
textHndl_fact_izq = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[0.7 2.55 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor izquierda',...
   'String','F. Izq:');

Accion_fact_izq=['fact_izq=str2num(get(editHndl_fact_izq,''String''));'];
editHndl_fact_izq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[1.7 2.65 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor izquierda',...
   'String',fact_izq, ...
   'CallBack',Accion_fact_izq);

%--------------------------------------------------------------------------%/// tiempo de pausa
textHndl_w0 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 4.65 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w0',...
   'String','w0:');

Accion_w0=['w0=str2num(get(editHndl_w0,''String''));'];
editHndl_w0=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 4.75 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w0',...
   'String',w0, ...
   'CallBack',Accion_w0);
%--------------------------------------------------------------------------/// w1
textHndl_w1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 3.95 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w1',...
   'String','w1:');

Accion_w1=['w1=str2num(get(editHndl_w1,''String''));'];
editHndl_w1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 4.05 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w1',...
   'String',w1, ...
   'CallBack',Accion_w1);
%--------------------------------------------------------------------------/// w2
textHndl_w2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 3.25 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','w2',...
   'String','w2:');

Accion_w2=['w2=str2num(get(editHndl_w2,''String''));'];
editHndl_w2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[3.7 3.35 1.2 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w2',...
   'String',w2, ...
   'CallBack',Accion_w2);
%--------------------------------------------------------------------------/// umbral
textHndl_pausa = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[3 2.55 1.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Pausa',...
   'String','T. Pausa:');

Accion_pausa=['pausa=str2num(get(editHndl_pausa,''String''));'];
editHndl_pausa=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[4.3 2.65 .6 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo de pause',...
   'String',pausa, ...
   'CallBack',Accion_pausa);

%--------------------------------------------------------------------------/// w0
textHndl_umbral = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 3.95 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Umbral del usuario',...
   'String','Umbral del usuario:');

Accion_umbral=['umbral=str2num(get(editHndl_umbral,''String''));'];
editHndl_umbral=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[7.8 4.05 1.3 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Umbral del usuario',...
   'String',umbral, ...
   'CallBack',Accion_umbral);
%--------------------------------------------------------------------------/// vel
textHndl_vel= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 3.25 3 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Velocidad de rotación de la flecha',...
   'String','Velocidad de rotación:');

Accion_popup_vel=['vel= get(popupHndl_vel,''Value'');'];
pop_string_vel=char(cell_vel(1));
for i= 2:3,
   pop_string_vel=[pop_string_vel '|' char(cell_vel(i))];
end;
popupHndl_vel = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[8.3 3.35 0.8 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_vel,...
   'Value',vel,...
   'CallBack',Accion_popup_vel);

%--------------------------------------------------------------- metodo de funcionamiento
textHndl_metodo = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 4.65 2.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Movimiento de flecha continuo o por impulsos',...
   'String','Funcionamiento:');

Accion_popup_metodo=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos:
      'metodo= get(popupHndl_metodo,''Value'');', ...
   ];

%Construccion del string del popup:
pop_string=char(cell_metodos(1));
for i= 2:2,
   pop_string=[pop_string '|' char(cell_metodos(i))];
end;
popupHndl_metodo = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[7.4 4.75 1.7 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string,...
   'Value',metodo,...
   'CallBack',Accion_popup_metodo);

%--------------------------------------------------------------------------/// w0
textHndl_tiempo_en_bloq= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[5.2 2.55 3.2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Tiempo para seleccionar un bloque',...
   'String','Tiempo de selección:');

Accion_tiempo_en_bloq=['tiempo_en_bloq=str2num(get(editHndl_tiempo_en_bloq,''String''));'];
editHndl_tiempo_en_bloq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[8.4 2.65 .7 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo necesario para que un bloque sea seleccionado',...
   'String',tiempo_en_bloq, ...
   'CallBack',Accion_tiempo_en_bloq);


%4---MENÚ DE BOTONES---------------------------------------------------------------------
frameHndl_botones=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[1.5 .45 7 1.5], ....
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');
%--------------------------------------------------------------------------pruebas tipo 1

Accion_push_iniciar=[...
        'set(pushHndl_iniciar,''Fontsize'',15,''String'',''Comienzo'');',...
        'if isempty(tamano|fc1|fc2|pausa|w0|w1|w2|fact_der|fact_izq|tiempo_en_bloq),',...
        'aviso([''Complete todos los parametros del panel''], figure(fig_sujeto));',...    
        'else,',...
        'save ensayo_config.mat fc1 fc2 pausa w0 w1 w2 fact_der fact_izq ', ...
        'mayus vel metodo color colorf tamano estilo grosor tiempo_en_bloq;', ...
        'Ensayo;',...
        'end'];

pushHndl_iniciar=uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[2 .7 6 1], ...
    'BackgroundColor',COLOR_FONDO_TEXTOS, ... %Color del fondo
    'ForegroundColor',[0 0 0], ...
    'FontSize',15,...
    'ToolTipString','Iniciar Ensayo con la configuración establecida',...
    'String','Iniciar aplicación', ...
	'CallBack',Accion_push_iniciar);

% ------------------------------------------------------------------------
% Menú superior donde están las opciones de Salir, salir de matlab, ayuda

labels = str2mat( ...
     '&Salir', ...
     '>&Salir de Sesion^s', ...
     '>-------', ...
     '>&Salir de Matlab^m', ...
     '&Ayuda' ...
     ); %labels
 
 call_Salir=[...
     'Sesion_Salir;'...
  ]; %Call_Salir

  call_SalirDeMatlab=[...
     'SalirDeMatlab;'...
  ]; %Call_SalirDeMatlab
calls = str2mat( ...
     '', ...
     call_Salir, ...	%es un programa que hay hecho
     '', ...
     call_SalirDeMatlab, ... %es un CallBack que hay hecho
     'Sesion_Ayuda' ... %Es un programa
     );
handles = makemenu(gcf, labels, calls);   
