%Pasa de los WARNINGS
Screensize=get(0,'Screensize'); %Tomo el tamaño de la pantalla; Deberia poder usarlo con
                                %'position' en las figuras, pero hace cosas raras.
AnchoS=Screensize(3);
AltoS=Screensize(4);
figs(2) = figure( 'Units','pixels', ...
            'position',[AnchoS/2-224 AltoS/2-64 448 128],...
            'Menubar','none',...
            'Colormap',bone(64),...
            'NumberTitle','off',...
            'Resize','Off');
        
IconAxes=axes( 'Units','pixels', ...
               'Position',[0 0 7*64 2*64], ...
               'HandleVisibility','on', ...
               'Tag','IconAxes');     

IconData=1:64;IconData=(IconData'*IconData)/64; %Cada numero de estos indica un color del
                                                %mapa de colores(Colormap) que hayamos elegido(bone)

Img=image('CData',IconData,'Parent',IconAxes);  
set(IconAxes, ...
      'XLim'            ,get(Img,'XData')+[-0.5 0.5], ...%XData me da la longitud en dir X de la Img
      'YLim'            ,get(Img,'YData')+[-0.5 0.5], ...%...dir Y...
      'Visible'         ,'off'                      , ...%Que no se vean los ejes
      'YDir'            ,'reverse'                  , ...      
      'HandleVisibility','callback' );
        %XLim e YLim marcan el rango de los ejes.
        
 
Font.FontUnits='pixels';
Font.FontSize=get(0,'FactoryUIControlFontSize');
Font.FontName=get(0,'FactoryUIControlFontName');
        


MsgHandle=uicontrol(figs(2), Font, ...
                   'Style','text', ...
                   'Units','pixels', ...
                   'Position',[155 100 140 18 ] , ...
                   'String',['¿Desea salir de Matlab?'], ...
                   'FontSize',12,...     
                   'Tag','MessageBox' , ...
                   'HorizontalAlignment','center' , ...    
                   'BackgroundColor'    ,[0 0 0] , ... %Lo suyo seria que hubiera un color trasparente
                   'ForegroundColor'    ,[0.8 0.9 1]    ... %Color del texto
                   );

    AccionSi = ['close all; clear all;',...
                'quit'];
SiHandle=uicontrol(figs(2), Font, ...
                  'Style','pushbutton' , ...
                  'Units','pixels', ...
                  'Position',[50 25 80 40]  , ...
                  'CallBack',AccionSi, ...
                  'FontSize',16,...
                  'String','Si'  , ...
                  'TooltipString', 'Saldra de Matlab y se cerraran todas las ventanas', ...
                  'HorizontalAlignment','center'   , ...
                  'Tag','SiButton');
             
NoHandle=uicontrol(figs(2), Font, ...
                  'Style','pushbutton' , ...
                  'Units','pixels', ...
                  'Position',[448-50-80 25 80 40]  , ...
                  'CallBack','delete(get(0,''CurrentFigure''))', ...
                  'FontSize',16,...
                  'String','No'  , ...
                  'TooltipString', 'volver al entorno en que estaba', ...
                  'HorizontalAlignment','center'   , ...
                  'Tag','NoButton');
               
set(0,'PointerLocation',[round(Screensize(3)/2) round(Screensize(4)/2)]);

uiwait(figs(2));  %Espera a que se pulse un boton dentro de la ventana, pero no trae cuenta porque
            %sin el, puede pulsarse tambien cualquier tecla. Lo q me gustaria es que se bloqueara
            %esa ventana y no se pudiera hacer otra cosa hasta que no se pulse el boton, claro
            %que quiza tampoco traiga cuenta, pq entonces tengo que hacer antes todas las ventanas
            %para poder verlas despues de 1 en 1.
            %PERO NO ME QUEDA MAS REMEDIO QUE USARLO PQ SINO, LA EJECUCION DEL PROGRAMA NO ESPERA.
            %prueba, prueba, con el y sin el y veras que divertido.
               
               
