%
% PANEL DE CONTROL
%
% Parte inicial de la aplicacion, organiza el panel y las figuras. Tambien
% capta las variables tales como 
% Frec de corte, Fact Der/Izq, w0, w1, w2, ... que sirven para el funcionamiento del programa
% Ajusta las figuras, las variables para modificar el texto, ... etc.
%
% Diagrama de Bloques de la Herramienta de Medida:
%
% Panel --> Ensayo --> Medir --> Prueba --> tiempo2frec --> Desp_barra --> Desplaza --> Selec_bloque --> Cadenas3 --> CreaCombianaciones --> Alg_Comprueba_Comb_válidas --> Escribe
%                      |                                  |                                           |
%                      ---> filtrar_eeg                   ---> filtrado                               ---> dibuja_cambio_predicción
%
% Vea tambien: pulsar
%
%
% Juan Antonio Lara Domínguez - Dpto. de Tecnología Electrónica - Universidad de Málaga - 2007
% Modificado: Francisco Velasco, Octubre 2008
%--------------------------------------------------------------------------------------------------------------

% Limpiar todo el entorno Matlab:
close all; %/ cerramos todas las figuras que haya abiertas
clear all; %/ Borra todas las variables y algunas cosas mas
global COLOR_FONDO color_texto;  %colores de la pantalla del sujeto
COLOR_FONDO_TEXTOS= [.5 .5 .5];             %Usado para el fondo de los frame, y logicamente el fondo de los textos
COLOR_FONDO=[1 1 1];                        %Color del fondo de los cuadros que rellena el usuario
color_texto=[0 0 0];                        % Color de texto del panel
global barra_min
global umbral_selec2
global closingFigure

global Fs tam_ventana solape orden t_cursor t_objetivo t_analisis d_analisis d_prueba;
alt=0.5;           %Altura

%/ Parametros de cada sujeto (a introducir en el panel)
global fc1 fc2 t_reset w0 w1 w2 fact_der fact_izq barThreshold tiempo_en_bloq t_pause sujeto sesion numVueltas mundo mundoVR

global metodo vel giro explore interfaz commandsNo reubicax ordenCom;             %Son los metodos de funcionamiento disponibles
% Indica el fin de la ejecución
global closingTime;
closingTime = 0;
mundo = 1;

cell_metodo={'Continuo' 'Discreto'};   %Usado para el menu pop-up
cell_vel={'1' '2' '3'};   %Usado para el menu pop-up
cell_giro={'Continuo' 'Discreto'};
cell_explore={'Evaluación' 'Objetivo'  'Pasillo'};
cell_interfaz={'Gráfica' 'Acústica' 'Ambos'};
cell_commands={'3' '4'};
cell_reubicax={'No' 'Si'};   
cell_ordenCom={'Sí' 'No'};


% ESTADÍSTICOS--------------
% cada una de las siguientes vbles será un vector de 4 posiciones, una para
% cada comando (avanzar, girar dcha,  girar izqd y atrás)
global num_vueltas t_total t_bloque num_eleccx t_invocax;
num_vueltas = [0 0 0 0];
t_total = [0 0 0 0];
t_bloque = [0 0 0 0];
num_eleccx = [0 0 0 0];
t_invocax = 0;

%---------------------------------------------------------------------

global cell_seleccion seleccion2             %NUEVO!!!!!!!!!!!!!!!!!!!!!!
cell_seleccion={'1' '2'};

%---------------------------------------------------------------configuración general de la ventana de texto

Fs=128;                %/ hay que poner 128(130 no)
tam_ventana=4;  %/ hay que poner 4(13 no)
solape=60;  %/ hay que poner 60(0 no) (ver tiempo2frec el tamaño)
orden=floor(tam_ventana/2);
t_cursor= 1;
t_objetivo= 3;
t_analisis= 4;
d_analisis= 5.6;
d_prueba=4000;
 % Existe el fichero de configuración, cargo las variables
if exist('AsincronoIntegrado/ensayo_config.mat','file') == 2            
     load ensayo_config;
     sesion = sesion + 1;     
else  
    fc1=8;           
    fc2=15; 
    t_reset=1;     
    w0=0;
    w1=1;  
    w2=0;
    fact_der=1;
    fact_izq=1; 
    tiempo_en_bloq=1;
    numVueltas = 2;
    vel=1;
    metodo=1;
    giro=1;
    explore = 1.;
    interfaz = 1.;
    seleccion2=1;
    barra_min=0.45;  
    umbral_selec2=0.6;
    t_pause = 2;
    sesion = 1;
    barThreshold = 0.7;
    commandsNo = 1;
    reubicax = 1;
    ordenCom = 1;
end,    

% Posiciones en cm
myWidth = 16;
myHeight = 6;
cols = 1.5 + myWidth * [0/8 1/8 2/8 3/8 4/8 5/8 6/8 7/8 8/8];
filas =3 + myHeight * [6/7 5/7 4/7 3/7 2/7 1/7 0/7];

%---------------------------------------------------- configuración general de la ventana del PANEL DE CONTROL
%--------------------------------------------------------------------------------------------------
global fig_panel;
fig_panel = 1;
figure(fig_panel);
set(figure(fig_panel), ...
	'NumberTitle','off', ...
	'Name','BCI Navigation through virtual worlds', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
    'KeyPressFcn',@pulsar, ...
    'Position',[10 10 myWidth+2 myHeight+4],...  
    'Pointer','arrow');
%---------------------------------------------------------------------variables ///21-2-07


%3---ORGANIZACIÓN DEL ENSAYO-----------------------------------------------------------------------------------
frameHndl_ensayo=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[1 2.5 myWidth myHeight+1], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');

%--------------------------------------------------------------- metodo de
%exploracion
textHndl_explore = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(1) 1.5 alt], ... 
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Evaluación o Búsqueda de objetivo',...
   'String','Modo');

Accion_popup_explore=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos
      'explore = get(popupHndl_explore,''Value'');', ...
   ];
%Construccion del string del popup
pop_string_explore=char(cell_explore(1));
for i= 2:3,
   pop_string_explore=[pop_string_explore '|' char(cell_explore(i))];
end;
popupHndl_explore = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(2) filas(1) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_explore,...
   'Value',explore,...
   'CallBack',Accion_popup_explore);

%--------------------------------------------------------------------------

%/// Identificador de sujeto
textHndl_sujeto = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(2) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Sujeto',...
   'String','Sujeto');

Accion_sujeto=['sujeto = get(editHndl_sujeto,''String'');'];
editHndl_sujeto=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(2) filas(2) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Sujeto',...
   'String',sujeto, ...
   'CallBack',Accion_sujeto);

%--------------------------------------------------------------- metodo de
%giro
textHndl_giro = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(3)  1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Giro continuo o discreto',...
   'String','Giro');

Accion_popup_giro=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos
      'giro = get(popupHndl_giro,''Value'');', ...
   ];
%Construccion del string del popup
pop_string_giro=char(cell_giro(1));
for i= 2:2,
   pop_string_giro=[pop_string_giro '|' char(cell_giro(i))];
end;
popupHndl_giro = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(2) filas(3) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_giro,...
   'Value',giro,...
   'CallBack',Accion_popup_giro);

%--------------------------------------------------------------- metodo de
%avance
textHndl_metodo = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(4) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Avance continuo o discreto',...
   'String','Avance');

Accion_popup_metodo=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos
      'metodo= get(popupHndl_metodo,''Value'');', ...
   ];
%Construccion del string del popup
pop_string=char(cell_metodo(1));
for i= 2:2,
   pop_string=[pop_string '|' char(cell_metodo(i))];
end;
popupHndl_metodo = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(2) filas(4) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string,...
   'Value',metodo,...
   'CallBack',Accion_popup_metodo);

%--------------------------------------------------------------------------
%///umbral de selección
textHndl_umbral = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(5) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Umbral Selección',...
   'String','Umbral Sel.');

Accion_umbral=['barThreshold=str2num(get(editHndl_umbral,''String''));'];
editHndl_umbral=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(2) filas(5) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Umbral del usuario',...
   'String',barThreshold, ...
   'CallBack',Accion_umbral);

%UMBRAL DE DETENCIÓN
textHndl_umbral_selec2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(6) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Umbral Detención',...
   'String','Umbral Det.');

Accion_umbral_selec2=['umbral_selec2=str2num(get(editHndl_umbral_selec2,''String''));'];
editHndl_umbral_selec2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(2) filas(6) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Umb.Det.',...
   'String',umbral_selec2, ...
   'CallBack',Accion_umbral_selec2);

%---------------------------- Orden comandos
textHndl_ordenCom= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(1) filas(7) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Cambiar el orden de los comandos tras el avance',...
   'String','Orden Com.');

Accion_popup_ordenCom=['ordenCom=  get(popupHndl_ordenCom,''Value'');'];
pop_string_ordenCom=char(cell_ordenCom(1));
for i= 2:2,
   pop_string_ordenCom=[pop_string_ordenCom '|' char(cell_ordenCom(i))];
end;
popupHndl_ordenCom = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(2) filas(7) 1 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_ordenCom,...
   'Value',ordenCom,...
   'CallBack',Accion_popup_ordenCom);

%-----------------------------Interfaz
textHndl_interfaz = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(1) 1.5 alt], ... 
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Tipo de interfaz',...
   'String','Interfaz');

Accion_popup_interfaz=[...%Asegurarse de que hay puntos suficientes para satisfacer el orden de los metodos
      'interfaz = get(popupHndl_interfaz,''Value'');', ...
   ];
%Construccion del string del popup
pop_string_interfaz=char(cell_interfaz(1));
for i= 2:3,
   pop_string_interfaz=[pop_string_interfaz '|' char(cell_interfaz(i))];
end;
popupHndl_interfaz = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(4) filas(1) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_interfaz,...
   'Value',interfaz,...
   'CallBack',Accion_popup_interfaz);

%--------------------------------------------------------------------------

%/// Identificador de sesion
textHndl_sesion = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(2) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Sesion',...
   'String','Sesion');

Accion_sesion=['sesion = str2num(get(editHndl_sesion,''String''));'];
editHndl_sesion=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(4) filas(2) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','sesion',...
   'String',sesion, ...
   'CallBack',Accion_sesion);


%--------------------------------------------------------------------------/// frec corte 1
textHndl_fc1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(3) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte inferior',...
   'String','Frec. Inf.');

Accion_fc1=['fc1=str2num(get(editHndl_fc1,''String''));'];
editHndl_fc1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(4) filas(3) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte inferior',...
   'String',fc1, ...
   'CallBack',Accion_fc1);
%--------------------------------------------------------------------------/// frec corte 2
textHndl_fc2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(4) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia de corte superior',...
   'String','Frec Sup.');

Accion_fc2=['fc2=str2num(get(editHndl_fc2,''String''));'];
editHndl_fc2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(4) filas(4) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia de corte superior',...
   'String',fc2, ...
   'CallBack',Accion_fc2);
%--------------------------------------------------------------------------/// fact_der
textHndl_fact_der = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(5) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor derecha',...
   'String','F. Der.');

Accion_fact_der=['fact_der=str2num(get(editHndl_fact_der,''String''));'];
editHndl_fact_der=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(4) filas(5) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor derecha',...
   'String',fact_der, ...
   'CallBack',Accion_fact_der);
%--------------------------------------------------------------------------/// fact_izq
textHndl_fact_izq = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(6) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Factor izquierda',...
   'String','F. Izq.');

Accion_fact_izq=['fact_izq=str2num(get(editHndl_fact_izq,''String''));'];
editHndl_fact_izq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(4) filas(6) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el factor izquierda',...
   'String',fact_izq, ...
   'CallBack',Accion_fact_izq);

%---------------------------- Carga de mundos
% Búsqueda de los posibles mundos .wrl
cadenaArchivos = dir('mundos/*.wrl');
textHndl_mundos= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(3) filas(7) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Mundos virtuales disponibles',...
   'String','Cargar mundo');

Accion_popup_mundos=['mundo = get(popupHndl_mundos,''Value'');'];
pop_string_mundos= 'Elige un mundo:';
for i= 1:length(cadenaArchivos),
   pop_string_mundos=[pop_string_mundos '|' cadenaArchivos(i).name];
end;
popupHndl_mundos = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(4) filas(7) 2 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_mundos,...
   'Value',mundo,...
   'CallBack',Accion_popup_mundos);

%--------------------------------------------------------------------------
%///Nº de vueltas
textHndl_numVueltas= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(1) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Número de vuletas antes de volver al NC',...
   'String','Nº de vueltas');

Accion_numVueltas=['numVueltas = str2num(get(editHndl_numVueltas,''String''));'];
editHndl_numVueltas=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(6) filas(1) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Nº de vueltas',...
   'String',numVueltas, ...
   'CallBack',Accion_numVueltas);


%------------------------------------------"modo de seleccion"

textHndl_seleccion2= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(2) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Método de selección de bloque',...
   'String','Mét.Selecc.');

Accion_popup_seleccion2=['seleccion2= get(popupHndl_seleccion2,''Value'');'];
pop_string_seleccion2=char(cell_seleccion(1));
for i= 2:2,
   pop_string_seleccion2=[pop_string_seleccion2 '|' char(cell_seleccion(i))];
end;
popupHndl_seleccion2 = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(6) filas(2) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_seleccion2,...
   'Value',seleccion2,...
   'CallBack',Accion_popup_seleccion2);


%--------------------------------------------------------------------------
%%///w0
textHndl_w0 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(3) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w0',...
   'String','w0');

Accion_w0=['w0=str2num(get(editHndl_w0,''String''));'];
editHndl_w0=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(6) filas(3) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w0',...
   'String',w0, ...
   'CallBack',Accion_w0);
%--------------------------------------------------------------------------/// w1
textHndl_w1 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(4) 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Frecuencia w1',...
   'String','w1');

Accion_w1=['w1=str2num(get(editHndl_w1,''String''));'];
editHndl_w1=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(6) filas(4) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w1',...
   'String',w1, ...
   'CallBack',Accion_w1);
%--------------------------------------------------------------------------/// w2
textHndl_w2 = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(5) 1 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','w2',...
   'String','w2');

Accion_w2=['w2=str2num(get(editHndl_w2,''String''));'];
editHndl_w2=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(6) filas(5) 1.5 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí la frecuencia w2',...
   'String',w2, ...
   'CallBack',Accion_w2);

%--------------------------------------------------------------------------
%/// vel de rotación
textHndl_vel= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(5) filas(6) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Velocidad de rotación de la flecha',...
   'String','Vel.  Rotación');

Accion_popup_vel=['vel= get(popupHndl_vel,''Value'');'];
pop_string_vel=char(cell_vel(1));
for i= 2:3,
   pop_string_vel=[pop_string_vel '|' char(cell_vel(i))];
end;
popupHndl_vel = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(6) filas(6) 1.5 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_vel,...
   'Value',vel,...
   'CallBack',Accion_popup_vel);


%--------------------------------------------------------------------------/// Tiempo de seleccion
textHndl_tiempo_en_bloq= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(1) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Tiempo para seleccionar un bloque',...
   'String','Tiempo Sel.');

Accion_tiempo_en_bloq=['tiempo_en_bloq = str2num(get(editHndl_tiempo_en_bloq,''String''));'];
editHndl_tiempo_en_bloq=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(8) filas(1) 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo necesario para que un bloque sea seleccionado',...
   'String',tiempo_en_bloq, ...
   'CallBack',Accion_tiempo_en_bloq);



%--------------------------------------------------------------------------
%/// T. Reset
textHndl_t_reset = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(2) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','t_reset',...
   'String','Tiempo Reset');

Accion_t_reset=['t_reset=str2num(get(editHndl_t_reset,''String''));'];
editHndl_t_reset=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(8) filas(2) 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo de pause',...
   'String',t_reset, ...
   'CallBack',Accion_t_reset);

% ------------------------------------------------------------------------

%/// T. Pause
textHndl_t_pause = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(3) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','t_pause',...
   'String','Tiempo Pausa');

Accion_t_pause=['t_pause=str2num(get(editHndl_t_pause,''String''));'];
editHndl_t_pause=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(8) filas(3) 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','Escriba aquí el tiempo de pausa',...
   'String',t_pause, ...
   'CallBack',Accion_t_pause);


%----------------------------Long mínima de la barra 

textHndl_barra_min = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(4) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','L.BAR',...
   'String','Long. Mín.');

Accion_barra_min=['barra_min=str2num(get(editHndl_barra_min,''String''));'];
editHndl_barra_min=uicontrol( ...
   'HorizontalAlignment','right',...
   'Style','edit', ...
   'Units','cent', ...
   'Position',[cols(8) filas(4) 1 alt], ...
   'Enable','on',...
   'BackgroundColor',COLOR_FONDO, ... %Color del fondo
   'ForegroundColor',color_texto, ...
   'ToolTipString','L.BAR',...
   'String',barra_min, ...
   'CallBack',Accion_barra_min);


%----------------------------Nº de comandos 

textHndl_commands= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(5) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Número comandos en la interfaz',...
   'String','Nº comandos');

Accion_popup_commands=['commandsNo=  get(popupHndl_commands,''Value'');'];
pop_string_commands=char(cell_commands(1));
for i= 2:2,
   pop_string_commands=[pop_string_commands '|' char(cell_commands(i))];
end;
popupHndl_commands = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(8) filas(5) 1 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_commands,...
   'Value',commandsNo,...
   'CallBack',Accion_popup_commands);

%----------------------------Reubicar tras colisión

textHndl_reubicax= uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[cols(7) filas(6) 2 alt], ...
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','Reubicar la posición en el centro del pasillo tras colisionar?',...
   'String','Reubicación');

Accion_popup_reubicax=['reubicax=  get(popupHndl_reubicax,''Value'');'];
pop_string_reubicax=char(cell_reubicax(1));
for i= 2:2,
   pop_string_reubicax=[pop_string_reubicax '|' char(cell_reubicax(i))];
end;
popupHndl_reubicax = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[cols(8) filas(6) 1 alt], ...
   'BackgroundColor',COLOR_FONDO, ...
   'ForegroundColor',color_texto, ...
   'String',pop_string_reubicax,...
   'Value',reubicax,...
   'CallBack',Accion_popup_reubicax);


%-----------------------------------------------------------------------

%4---MENÚ DE BOTONES---------------------------------------------------------------------
frameHndl_botones=uicontrol( ...
   'Style','frame', ...
   'Units','cent', ...
   'Position',[5 .5 7 1.5], ....
   'BackgroundColor',COLOR_FONDO_TEXTOS, ...
   'ForegroundColor',[1 1 1], ...
   'String','Frame');


Accion_push_iniciar=[...        
        'if ( isempty( fc1|fc2|t_reset|w0|w1|w2|fact_der|fact_izq|tiempo_en_bloq|t_pause|sujeto|sesion|numVueltas ) | (mundo == 1) )',...
            'fig_aviso = 3;',...
            'figure(fig_aviso);',...
            'aviso([''Complete todos los parametros del panel''], figure(fig_aviso));',...    
        'else,',...
            'mundoVR = cadenaArchivos(mundo-1).name;',...
            'save ensayo_config.mat fc1 fc2 t_reset w0 w1 w2 fact_der fact_izq t_pause explore interfaz commandsNo reubicax  ', ...
            'vel metodo seleccion2 barra_min umbral_selec2 tiempo_en_bloq sujeto sesion giro barThreshold numVueltas ordenCom mundoVR;', ...    
            'close(fig_panel);',... 
            'StartVR;',...
            'Ensayo2;',...            
        'end'];       
pushHndl_iniciar=uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[5.5 0.75 6 1], ...
    'BackgroundColor',COLOR_FONDO_TEXTOS, ... %Color del fondo
    'ForegroundColor',[0 0 0], ...
    'FontSize',15,...
    'ToolTipString','Iniciar Ensayo con la configuración establecida',...
    'String','Iniciar aplicación', ...
	'CallBack',Accion_push_iniciar);



%--------------------------------------------------------------------------
% Una figura que detecta la pulsación de una tecla y cierra la aplicación

closingFigure = 2;
set(figure(closingFigure),'WindowStyle','normal',...   
                'visible','on',...
                'Resize','off',...
                'Name','Cerrar aplicación',...
                'MenuBar','none',...
                'ToolBar','none',...
                'Selected','off',...
                'NumberTitle', 'off',...
                'KeyPressFcn','closingTime = 1;',...               
                'Position', [0,-20,100,10]); 
figure(closingFigure);       
%-------------------------
labels = str2mat( ...
     '&Salir', ...
     '>&Salir de Sesion^s', ...
     '>-------', ...
     '>&Salir de Matlab^m', ...
     '&Ayuda' ...
     ); %labels
 
 call_Salir=[...
     'Sesion_Salir;'...
  ]; %Call_Salir

  call_SalirDeMatlab=[...
     'SalirDeMatlab;'...
  ]; %Call_SalirDeMatlab
calls = str2mat( ...
     '', ...
     call_Salir, ...	%es un programa que hay hecho
     '', ...
     call_SalirDeMatlab, ... %es un CallBack que hay hecho
     'Sesion_Ayuda' ... %Es un programa
     );
handles = makemenu(gcf, labels, calls);   

