% Sesion_Ayuda: programa que gestiona la ayuda del Panel de Control de Sesiones

figs(2)=figure(2);
set(figs(2), ...
	'NumberTitle','off', ...
	'Name','D.T.E. - Proyecto IHMAN - BCI - Ayuda de Sesion', ...
	'Resize','off', ...
	'MenuBar','none', ...
	'Units','cent', ...
	'Position',[5 2 15 13], ...
   'Pointer','arrow');
%'Position',[posicion(1) posicion(2) 15 10], ...


%-------------------------------------------------------------------Tamaño de la Ventana
mensaje0=[...
        'Proyecto IHMAN -BCI                               '...%continua en la misma linea
        '                                                  ';...%linea siguient
        'Departamento de Tecnologia Electronica            '... 
        '                                                  ';...e
        'Escuela Tecnica Superior de Ingenieros de Telecomu'...
        'nicacion de Malaga                                ';...
        'Campus de Teatinos                                '...
        '                                                  ';...
        '                                                  '...
        'Profesor Tutor: Ricardo Ron Angevin               ';...
        '                                                  '...
        'Alumno: Juan de la Torre Pelaez                   ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  '];
mensaje1=[...
        'Este programa sirve para organizar sesiones, para '... %continua en la misma linea
        'ello ayuda a configurar totalmente un ensayo y    ';...%linea siguiente
        'realizarlo. Cuando termina, vuelve a la misma pant'...
        'alla para organizar el siguiente.                 ';...
        'Una SESIÓN está formada por un conjunto de ENSAYOS'...
        ', cada uno de los cuales está dividido a su vez en';...
        'distintas PRUEBAS:                                '...
        '                                                  ';...
        '- Cada PRUEBA consiste en un ejercicio diferenciad'...
        'o para el sujeto, en él se le pedirá que se con-  ';...
        '  centre en realizar determinada ACTIVIDAD, que en'...
        ' general será relajarse, pensar algo, o realizar  ';...
        ' algún movimiento. Así una prueba suele durar unos'...
        'pocos segundos.                                   ';...
        '- Cada prueba puede dividirse en INTENTOS, de los '...
        'cuales no tiene porqué ser consciente el sujeto,  ';...
        '  generalmente:                                   '...
        '                                                  ';...
        '  ·Cada Intento corresponde con una evaluación del'...
        ' EEG del sujeto, y determinará un movimiento del  ';...
        '   cursor(que se realimenta hacia el sujeto, pues '...
        'este ve el resultado de su esfuerzo en la         ';...
        '  pantalla).                                      '...
        '                                                  ';...
        '- ENSAYO es un conjunto de pruebas que definen un '...
        'experimento, podemos organizar las pruebas que    ';...
        'forman cada ensayo de distinta manera:            '...
        '                                                  ';...
        '  ·Ej.1: Pedir al sujeto que haga lo que quiera, s'...
        'e supone que no sabe nada acerca del funciona-    ';...
        '  miento del sistema y sólo pretendemos ver sus ni'...
        'velesd e respuesta, o el BW de sus señales alpha. ';...
        '  En este caso, quizá sea mejor que el sujeto no m'...
        'ire la pantalla, ni reciba estimulos externos.    ';...
        '  ·Ej.2: Pedir al sujeto que se concentre en una ú'...
        'nica Actividad, con el fin de que practique solo  ';...
        'esa.                                              '...
        '                                                  ';...
        '  ·Ej.3: Organizar Ensayos con Actividades(=>Prueb'...
        'as) alternativas, para que el sujeto se esfuerze  ';...
        '  mas, al tener que cambiar de Actividad.         '...
        '- Llamaremos SESIÓN al conjunto de ensayos que se ';...
        'realizan en un mismo día.                         '...
        '                                                  ';...
        'Generalmente guardaremos los distintos Ensayos en '...
        'un directorio que indique datos sobre la sesión.  ';...
        '                                                  '...
        '                                                  ';...
        '--------> Esquema de un ENSAYO:                   '...
        '                                                  ';...
        'Los intentos están marcados con el carácter "^":  '...
        '                                                  ';...
        '                                                  '...
        '                                                  ';...
        '  Prueba 1          Prueba 2          Prueba 3    '...
        '                     Prueba 20                    ';...
        '|                       |                         '...
        '     |                         |                  ';...
        '  ^ ^ ^ ^ ... ^     ^ ^ ^ ^ ... ^   ^ ^ ^ ^ ... ^ '...
        '                             ^ ^ ^ ^ ... ^        '];
mensaje2=[...
        'Este programa sirve para organizar sesiones, para '... %continua en la misma linea
        'ello ayuda a configurar totalmente un ensayo y    ';...%linea siguiente
        'realizarlo. Cuando termina, vuelve a la misma pant'...
        'alla para organizar el siguiente.                 ';...
        'Se observa que el panel está dividido en varios ca'...
        'jetines:                                          ';...
        '                                                  '...
        '                                                  ';...
        '- En el superior se indica el nombre completo del '...
        'sujeto en el campo "Sujeto"; un nombre corto para ';...
        'referirnos a el(campo "Identificador"), y que será' ...
        ' util para crear un fichero de info adicional del ';...
        'sujeto. Ademas tambien tenemos un campo para dar n'...
        'ombre al Ensayo(campo "Nombre del Ensayo"), y     ';...
        'un campo indicando la fecha en que estamos. Se rec'...
        'omienda rellenar los campos Identificador y Nombre';...
        'del Ensayo porque se utilizan para crear directori'...
        'os y ficheros.                                    ';...
        '- En el segundo cajetin se define como va a ser el'...
        ' ensayo, cuántas pruebas va a tener y de que tipo.';...
        'A la derecha observamos 4 botones de configuracion'...
        'rapida y otro para crear un fichero de texto en el';...
        'que podemos guardar informacion adicional de nuest'...
        'ro sujeto.                                        ';...
        '- En el tercer cajetin, se indica la frecuencia de'...
        'muestreo a la que queremos grabar, el tamaño de   ';...
        'las ventanas que vamos a usar para hacer la estima'...
        'cion espectral, y el orden del metodo de Estima-  ';...
        'cion espectral que vamos a usar. Por cuestiones te'...
        'oricas el orden del metodo no puede ser superior a';...
        'la mitad del tamaño de la ventana. Se dispone ade-'...
        'mas de otros 4 cajetines para indcar los canales  ';...
        'que queremos grabar y el nombre que queremos darle'...
        's.                                                ';...
        'Finalmente hay otros 4 cajetines para indicar los '...
        'tiempos necesarios para cada prueba.              ';...
        '                                                  '...
        '                                                  ';...
        ' Abajo tenemos finalmente algunos botones mas:    '...
        '                                                  ';...
        '- El mas grande sirve para iniciar la sesion y una'...
        ' vez pulsado, nos pedira que comprobemos las cone-';...
        'xiones y lo pulsemos de nuevo para continuar.     '...
        '                                                  ';...
        '- Observamos otros dos botones: Ver(t) y Ver(f) qu'...
        'e sirven para poder ver o no las señales mientras ';...
        'son tomadas.                                      '...
        '                                                  ';...
        '- Boton de Configuracion Avanzada: nos permite man'...
        'ipular ciertos parametros de los anteriormente    ';...
        'comentados, que en la configuracion por defecto no'...
        ' es posible manipular(quedan en tono mas oscuro). ';...
        '- Finalmente hay un boton para resetear los todos '...
        'los parametros a una configuracion inicial, que es';...
        'con la que se decidio hacer los estudios originalm'...
        'ente.                                             ';...
        '                                                  '...
        '                                                  ';...
        '                                                  '...
        '                                                  '];
mensaje=[mensaje0 mensaje1 mensaje2]; %Concatenamos todos los msjs para tratarlos mas comodamente

%----------------------------------------------------------------------------UICONTROLS:
%------------------------------------------------------------Cuadro de texto para el msj
textHndl_mensaje = uicontrol( ...
   'HorizontalAlignment','left',...
   'Style','text', ...
   'Units','cent', ...
   'Position',[.5 .5 14 11], ...
   'BackgroundColor',[0.5 0.5 0.5], ...
   'ForegroundColor',[1 1 1], ...
   'ToolTipString','',...
   'String',mensaje0);

%------------------------------------------------------------------------ Botón Anterior
Accion_anterior= [...
        'ayuda = get(popup_ayuda,''Value'');',... %Se movera entre 1 y el numero de ayudas
        '',...                                    %que debera ser igual a length(mensaje)/100
        '',...                                    %Cada mensaje es una matriz 30*100
        'ayuda = ayuda -1;',... %Se movera entre 0 y length(mensaje)/100 - 1
        'if ayuda==0, ayuda=length(mensaje)/100; end;',...%Si es 0, hay que rotar y volver al ultimo
        'set(popup_ayuda,''Value'',ayuda);',...
        'set(textHndl_mensaje,''String'',mensaje(:,(ayuda-1)*100+1:ayuda*100));',...
    ]; 

pushHndl_anterior= uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[0.5 12 2 alt], ...
    'BackgroundColor',[0.5 0.5 0.5], ... %Color del fondo
    'ForegroundColor',[1 1 1], ...
    'ToolTipString','Ver ayuda anterior',...
    'String','<< Anterior', ...
	'CallBack',Accion_anterior);


%----------------------------------------------------------------------- Botón Siguiente
Accion_siguiente= [...
        'ayuda = get(popup_ayuda,''Value'');',... %Se movera entre 1 y el numero de ayudas
        '',...                                    %que debera ser igual a length(mensaje)/100
        '',...                                    %Cada mensaje es una matriz 30*100
        'ayuda = ayuda +1;',... %Se movera entre 0 y length(mensaje)/100 - 1
        'if ayuda==length(mensaje)/100+1, ayuda=1; end;',...%Si es 0, hay que rotar y volver al ultimo
        'set(popup_ayuda,''Value'',ayuda);',...
        'set(textHndl_mensaje,''String'',mensaje(:,(ayuda-1)*100+1:ayuda*100));',...
    ]; 
pushHndl_siguiente= uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[2.5 12 2 alt], ...
    'BackgroundColor',[0.5 0.5 0.5], ... %Color del fondo
    'ForegroundColor',[1 1 1], ...
    'ToolTipString','Ver siguiente ayuda',...
    'String','Siguiente >>', ...
	'CallBack',Accion_siguiente);

%--------------------------------------------------------------------------- Menu Pop-up
Accionpopup_ayuda=[...
        'ayuda = get(popup_ayuda,''Value'');',...
        'if ayuda==1, set(textHndl_mensaje,''String'',mensaje1);',...
        'elseif ayuda==2, set(textHndl_mensaje,''String'',mensaje2);',...
        'else,',... %supongo que quiere salir
        'close gcf; end;',...
    ];
popup_ayuda = uicontrol( ...
   'Style','popup', ...
   'Units','cent', ...
   'Position',[4.5 12 5 alt], ...
   'BackgroundColor',[0 0 0], ...
   'ForegroundColor',[1 1 1], ...
   'String','Miscelanea|Organizacion de las Sesiones|Funcionamiento General|Salir', ...
   'ToolTipString','Elija la ayuda',...
   'Value',1, ...
   'CallBack',Accionpopup_ayuda);


%--------------------------------------------------------------- Botón Salir de la Ayuda
Accion_salir= [...
        'close gcf;'
    ]; 
pushHndl_salir= uicontrol( ...
    'Style','pushbutton', ...
    'Units','cent', ...
    'Position',[9.5 12 2 alt], ...
    'BackgroundColor',[0.5 0.5 0.5], ... %Color del fondo
    'ForegroundColor',[1 1 1], ...
    'ToolTipString','Salir de la Ayuda',...
    'String','Salir', ...
	'CallBack',Accion_salir);
