
global ver_t ver_f

Screensize=get(0,'Screensize'); 

AnchoS=Screensize(3);
AltoS=Screensize(4);
figs(2)=figure(2);
set(figs(2), 'Units','pixels', ...
            'position',[AnchoS/2-224 AltoS/2-64 448 128],...
            'Menubar','none',...
            'Colormap',bone(64),...
            'NumberTitle','off',...
            'Resize','Off');
        
IconAxes=axes( 'Units','pixels', ...
               'Position',[0 0 7*64 2*64], ...
               'HandleVisibility','on', ...
               'Tag','IconAxes');     

IconData=1:64;IconData=(IconData'*IconData)/64; 

Img=image('CData',IconData,'Parent',IconAxes);  
set(IconAxes, ...
      'XLim'            ,get(Img,'XData')+[-0.5 0.5], ...
      'YLim'            ,get(Img,'YData')+[-0.5 0.5], ...
      'Visible'         ,'off'                      , ...
      'YDir'            ,'reverse'                  , ...      
      'HandleVisibility','callback' );
        
 
Font.FontUnits='pixels';
Font.FontSize=get(0,'FactoryUIControlFontSize');
Font.FontName=get(0,'FactoryUIControlFontName');
        


MsgHandle=uicontrol(figs(2), Font, ...
                   'Style','text', ...
                   'Units','pixels', ...
                   'Position',[16 100 197 18 ] , ...
                   'String','Salir de Sesión.m, ¿Esta seguro?', ...
                   'Tag','MessageBox' , ...
                   'HorizontalAlignment','left' , ...    
                   'BackgroundColor'    ,[0 0 0] , ... 
                   'ForegroundColor'    ,[0.8 0.9 1]    ... 
                   );
                
                
AccionSi = [...
      'close all;',...
      'clear all;',...
      'break']; 
SiHandle=uicontrol('Style','pushbutton' , ...
                  'Units','pixels', ...
                  'Position',[50 25 80 40]  , ...
                  'CallBack',AccionSi, ...
                  'String','Si'  , ...
                  'TooltipString', 'AccionSi', ...
                  'HorizontalAlignment','center' ...
                  );

              
AccionNo = ['delete(get(0,''CurrentFigure''))'];

NoHandle=uicontrol('Style','pushbutton' , ...
                  'Units','pixels', ...
                  'Position',[448-50-80 25 80 40], ...
                  'CallBack',AccionNo, ...
                  'String','No', ...
                  'TooltipString', 'Volver al entorno en que estaba', ...
                  'HorizontalAlignment','center' ...
                  );
        

set(0,'PointerLocation',[round(Screensize(3)/2) round(Screensize(4)/2)]);

uiwait(figs(2));
               